export const TableData = [
  {
    id: 'a07550b7-ef3f-4966-9d7b-fe8d64efe848',
    firstName: 'Brenda',
    lastName: 'Praill',
    email: 'bpraill0@adobe.com',
    country: 'Portugal',
    timezone: 'Europe/Lisbon',
    currency: 'EUR',
    company: 'Sawayn-Cruickshank',
    jobTitle: 'Professor',
    skills: ['DTE', 'ETL Tools', 'Blackberry', 'Crisis Intervention', 'ETL'],
  },
  {
    id: '22f024ba-3d7e-4393-a61d-2e2589207eec',
    firstName: 'Elias',
    lastName: 'Riggulsford',
    email: 'eriggulsford1@nydailynews.com',
    country: 'Malta',
    timezone: 'Europe/Malta',
    currency: 'EUR',
    company: 'Pacocha, Ondricka and Ondricka',
    jobTitle: 'Senior Sales Associate',
    skills: [
      'Adobe Acrobat',
      'LDRA',
      'ADP Payroll',
      'MPBN',
      'Object Oriented Software',
    ],
  },
  {
    id: '01dfc27d-c874-4a1f-9f5f-f8aa49eea2fa',
    firstName: 'Florentia',
    lastName: 'Halbeard',
    email: 'fhalbeard2@woothemes.com',
    country: 'Portugal',
    timezone: 'Europe/Lisbon',
    currency: 'EUR',
    company: 'McGlynn Group',
    jobTitle: 'Software Consultant',
    skills: [
      'HPLC-MS',
      'Customer Engagement',
      'Criminal Law',
      'Healthy Eating',
      'Class Actions',
    ],
  },
  {
    id: 'eedd5fa9-beb0-4001-a490-17f68dfcf5fe',
    firstName: 'Darryl',
    lastName: 'Gayther',
    email: 'dgayther3@surveymonkey.com',
    country: 'Czech Republic',
    timezone: 'Europe/Prague',
    currency: 'CZK',
    company: 'Reichert, Legros and Cruickshank',
    jobTitle: 'Accounting Assistant II',
    skills: ['Grassroots', 'Canon XL2', 'YUI', 'Pre-sales', 'PKI'],
  },
  {
    id: '9c123cd5-d7c9-43f1-bd6e-8a4213ff7122',
    firstName: 'Karrie',
    lastName: 'Cridland',
    email: 'kcridland4@tinyurl.com',
    country: 'Czech Republic',
    timezone: 'Europe/Prague',
    currency: 'CZK',
    company: 'Padberg Inc',
    jobTitle: 'Structural Analysis Engineer',
    skills: ['RSVP-TE', 'Gourmet', 'SVM', 'Underwriting', 'Pyrosequencing'],
  },
];
